version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
